spring:
 application:
  name: spring-cloud-consul
 cloud:
  consul:
   config: 
    prefix: config
    defaultContext: helloService
   discovery: 
    instanceId: ${spring.application.name}:${spring.application.instance.id:${random.value}}
    healthCheckPath: /${spring.application.name}/health
    healthCheckInterval: 15s
    tags: foo, bar
endpoints:
 shutdown:
  enabled: true       
logging:
  level:
    org.springframework.cloud.consul: INFO  
  